import { useEffect, useState } from 'react'
import { Save } from 'lucide-react'
import { DEFAULT_HEADER_CONFIG, type HeaderConfig, type Menu } from '@hiccms/appearance-manager'
import { appearanceApi } from '../../lib/appearance-api'

export default function HeaderBuilder() {
  const [config, setConfig] = useState<HeaderConfig>(DEFAULT_HEADER_CONFIG); const [menus, setMenus] = useState<Menu[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { Promise.all([appearanceApi.layout(), appearanceApi.menus()]).then(([layout, menuResult]) => { setConfig(layout.data.header); setMenus(menuResult.data) }).catch((error) => setMessage(error.message)) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await appearanceApi.updateHeader(config); setMessage('Header configuration tersimpan.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Gagal menyimpan') } }
  return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-5 rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Header Builder</h2><label className="block text-sm font-medium">Primary Menu<select value={config.menuSlug} onChange={(e) => setConfig({ ...config, menuSlug: e.target.value })} className="mt-1 w-full rounded-lg border bg-white px-3 py-2">{menus.map((menu) => <option key={menu.id} value={menu.slug}>{menu.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2">{[['showLogo', 'Tampilkan Logo'], ['showSiteName', 'Tampilkan Nama Situs'], ['sticky', 'Sticky Header']].map(([key, label]) => <label key={key} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={Boolean(config[key as keyof HeaderConfig])} onChange={(e) => setConfig({ ...config, [key]: e.target.checked })} />{label}</label>)}</div><label className="block text-sm font-medium">Alignment<select value={config.alignment} onChange={(e) => setConfig({ ...config, alignment: e.target.value as HeaderConfig['alignment'] })} className="mt-1 w-full rounded-lg border bg-white px-3 py-2"><option value="left">Left</option><option value="center">Center</option><option value="space-between">Space Between</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">CTA Label<input value={config.ctaLabel} onChange={(e) => setConfig({ ...config, ctaLabel: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm font-medium">CTA URL<input value={config.ctaUrl} onChange={(e) => setConfig({ ...config, ctaUrl: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2" /></label></div><button className="inline-flex items-center rounded-lg bg-blue-600 px-5 py-2 text-white"><Save className="mr-2 h-4 w-4" />Simpan Header</button>{message && <p className="text-sm text-blue-700">{message}</p>}</form>
}
